---

- name: Copy Traefik config for Gotify application
  ansible.builtin.template:
    src:  '{{ public_dotfiles_path }}/gotify/gotify.traefik.yml'
    dest: '{{ traefik_mount_config_path }}/dynamic_conf/gotify.traefik.yml'
