---

- name: Add PiHole DNS entry for Gotify
  import_tasks: '{{ ansible_roles_path }}/pihole/tasks/pihole_add_dns_entry.yml'
  vars:
    params_app_name: 'gotify'
    params_domain:   '{{ gotify_domain }}'
    params_ip:       '{{ traefik_macvlan_ip }}'
