---

- name: Copy Traefik config for Watchtower application
  ansible.builtin.template:
    src:  '{{ public_dotfiles_path }}/watchtower/watchtower.traefik.yml'
    dest: '{{ traefik_mount_config_path }}/dynamic_conf/watchtower.traefik.yml'
