---

- name: Ensure the project directory exists
  ansible.builtin.file:
    path:  '{{ watchtower_project_path }}'
    state: directory

- name: Copy docker-compose.yml
  ansible.builtin.template:
    src:  '{{ dockerfiles_path }}/watchtower/docker-compose.yml'
    dest: '{{ watchtower_project_path }}/docker-compose.yml'

- name: Copy Watchtower environment file
  ansible.builtin.template:
    src:  '{{ public_dotfiles_path }}/watchtower/watchtower.env'
    dest: '{{ watchtower_mount_config_path }}/watchtower.env'

- name: Start the Watchtower stack
  become: yes
  community.docker.docker_compose:
    project_src: '{{ watchtower_project_path }}'
    pull:        yes
    state:       present
