---

- name: Ensure user fonts directory
  ansible.builtin.file:
    state: directory
    path: "/home/{{ user_name }}/.local/share/fonts"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"

- name: Ensure config dir for fontconfig
  ansible.builtin.file:
    state: directory
    path: '/home/{{ user_name }}/.config/fontconfig/conf.d/'
    owner: "{{ user_name }}"
    group: "{{ user_group }}"

      #- name: Configure a fallback font for emojis
      #  ansible.builtin.copy:
      #    src: 'files/50-emoji-fallback.conf'
      #    dest: '/home/{{ user_name }}/.config/fontconfig/conf.d/50-emoji-fallback.conf'
