---

- name: Download Hack Nerd Font
  ansible.builtin.get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip
    dest: "/home/{{ user_name }}/.local/share/fonts/Hack.zip"

- name: Unpack the Hack Nerd Font
  ansible.builtin.unarchive:
    src: "/home/{{ user_name }}/.local/share/fonts/Hack.zip"
    dest: "/home/{{ user_name }}/.local/share/fonts/"
    remote_src: yes

- name: Remove the archive
  ansible.builtin.file:
    state: absent
    path: "/home/{{ user_name }}/.local/share/fonts/Hack.zip"

