---

- name: Add simple DNS entry to Pi-Hole
  become: yes
  ansible.builtin.template:
    src:  '{{ public_dotfiles_path }}/pihole/dnsmasq-custom.conf.j2'
    dest: '{{ pihole_mount_dnsmasq_path }}/99-{{ params_app_name }}.conf'
    owner: 'root'
    group: 'root'
    mode:  'u=rw,g=r,o=r'

- name: Add local 'hosts' file entry for Synology
  become: yes
  ansible.builtin.lineinfile:
    path:   /etc/hosts
    regexp: '^{{ params_ip }} {{ params_domain }}'
    line:   '{{ params_ip }} {{ params_domain }}'

- name: Restart Pi-Hole DNS server
  become: yes
  ansible.builtin.shell: /bin/docker-compose exec --detach pihole pihole restartdns
  args:
    chdir: '{{ pihole_project_path }}'
    warn:  no
