---

- name: Add PiHole DNS entry
  import_tasks: '{{ ansible_roles_path }}/pihole/tasks/pihole_add_dns_entry.yml'
  vars:
    params_app_name: 'traefik'
    params_domain:   '{{ traefik_domain }}'
    params_ip:       '{{ traefik_macvlan_ip }}'
